version: "3.1"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgData:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgData:
