version: "3"

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - appnetwork
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    # container_name: social-media-api
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    networks:
      - appnetwork

    environment:
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_URL=databseurl
      - JWT_SECRET=somesecret
      - JWT_EXPIRY=expiry
      - CLOUDINARY_BUCKET=bucketname
      - CLOUDINARY_KEY=key
      - CLOUDINARY_SECRET=secret
    command: ["npm", "run", "deploy"]

volumes:
  postgresdata:

networks:
  appnetwork:
